version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/deploy/sfu-vps"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "[IMP] compose:"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "[IMP] ci:"
    schedule:
      interval: "weekly"
