services:
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - ./prometheus/recording-rules.yml:/etc/prometheus/recording-rules.yml:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana-oss
    depends_on:
      - prometheus
      - loki
      - tempo
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

  alertmanager:
    image: prom/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  blackbox-exporter:
    image: prom/blackbox-exporter
    command:
      - --config.file=/etc/blackbox_exporter/config.yml
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro

  node-exporter:
    image: prom/node-exporter
    profiles:
      - linux-infra
    ports:
      - "9100:9100"
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    profiles:
      - linux-infra
    ports:
      - "8081:8080"
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    depends_on:
      - loki
      - tempo
    command:
      - --config=/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - ./data/logs:/var/log/o-sfu:ro

  loki:
    image: grafana/loki
    command:
      - -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
      - ./data/loki:/var/lib/loki

  tempo:
    image: grafana/tempo:2.9.0
    command:
      - -config.file=/etc/tempo/config.yaml
    ports:
      - "3200:3200"
    volumes:
      - ./tempo/config.yaml:/etc/tempo/config.yaml:ro
      - ./data/tempo:/var/tempo
