receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include:
      - /var/log/o-sfu/*.jsonl
    start_at: beginning
    include_file_path: true
    operators:
      - type: json_parser

processors:
  batch:

exporters:
  debug:
    verbosity: basic
  otlp_http/tempo:
    endpoint: http://tempo:4318
  otlp_http/loki:
    endpoint: http://loki:3100/otlp

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - otlp_http/tempo
    logs:
      receivers:
        - filelog
      processors:
        - batch
      exporters:
        - debug
        - otlp_http/loki
