apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity
    access: proxy
    editable: false
    jsonData:
      httpHeaderName1: Authorization
      allowedHosts:
        - "http://host.docker.internal:8070"
    secureJsonData:
      httpHeaderValue1: "Bearer $DIAGNOSTICS_AUTH_TOKEN"
